// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnimpmwltkgwkgswkqkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaW1wbXdsdGtnd2tnc3drcWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzkxODIsImV4cCI6MjA2Nzk1NTE4Mn0.-AwaP1CGkQ5zcLljcboxupitjUwsgtyqsA2GbvzQpVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});